document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
document.writeln("<title>链接安全保障 - 500福利导航</title>");
document.writeln("<meta name=\"keywords\" content=\"500导航,500福利导航,500福利导航地址,提交收录,广告合作,联系我们,500福利导航导航,500福利导航官网\">");
document.writeln("<meta name=\"description\" content=\"500导航入口首家上线链接安全保障赔付计划！\">");
document.writeln("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">");
document.writeln("<meta name=\"viewport\" content=\"width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\">");
document.writeln("<meta http-equiv=\"Cache-Control\" content=\"no-transform\">");
document.writeln("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\">");
document.writeln("<meta name=\"applicable-device\" content=\"pc,mobile\">");
document.writeln("<meta name=\"MobileOptimized\" content=\"width\">");
document.writeln("<meta name=\"HandheldFriendly\" content=\"true\">");
document.writeln("<meta name=\"author\" content=\"MMWZ\">");
document.writeln("<link rel=\"stylesheet\" href=\"css/faq.css?v=2022\">");
document.writeln("<link rel=\"stylesheet\" href=\"//s2.pstatp.com/cdn/expire-1-M/font-awesome/4.7.0/css/font-awesome.min.css\">");
document.writeln("");
document.writeln("<link rel=\"shortcut icon\" href=\"favicon.ico\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div id=\"container\">");
document.writeln("<div class=\"nav\">");
document.writeln("<a href=\"../\" target=\"_self\" style=\"color:white;font-weight:bold\"><li>首 页</li></a>");
document.writeln("<a href=\"faq.html#ads\" target=\"_blank\" style=\"color:white;font-weight:bold\"><li>合 作</li></a>");
document.writeln("<a href=\"faq.html#contact\" target=\"_blank\" style=\"color:white;font-weight:bold\"><li>联 络</li></a>");
document.writeln("<a href=\"faq.html#log\" target=\"_blank\" style=\"color:white;font-weight:bold\"><li>更 新</li></a>");
document.writeln("<a href=\"https://500fabu.com\" target=\"_blank\" style=\"color:white;font-weight:bold\"><li>地址发布</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<p style=\"background:#fffce7;margin:0 0 10px;padding:10px;font-size:13px;color:red;border-radius:5px;\">");
document.writeln("<span style=\"display:inline-block;background:#DA634B;color:#fff;font-weight:bold;padding:2px 8px;border-radius:2px;\"><i class=\"fa fa-bullhorn\" aria-hidden=\"true\"></i> 友情提示</span>&nbsp;&nbsp;近期500福利导航网站频繁遭到无良小人粗暴的山寨抄袭，请访客注意辨别真伪，以免上当受骗！");
document.writeln("</p>");
document.writeln("");
document.writeln("<div class=\"cate\" id=\"about\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-shield\" aria-hidden=\"true\"></i> 安全保障计划</p>");
document.writeln("</div>");
document.writeln("<a><li>为了保障所有访客的财产安全</li></a>");
document.writeln("<a><li>500福利导航网站首家上线链接安全保障赔付计划</li></a>");
document.writeln("<a><li>凡是在访问本站时遭遇的经济损失</li></a>");
document.writeln("<a><li>将得到100%全额赔付</li></a>");
document.writeln("<a><li>让您在访问本站的时候免除后顾之忧！</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"ads\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-user\" aria-hidden=\"true\"></i> 保障范围</p>");
document.writeln("</div>");
document.writeln("<a><li>1、不限地区的保障所有500导航的访客;</li></a>");
document.writeln("<a><li>2、因访问本站直接点出网址(不限于广告链接)造成的人身财产损失;</li></a>");
document.writeln("<a><li>3、因访问本站直接点出网址遭遇的电信网络诈骗行为；</li></a>");
document.writeln("<a><li>4、因访问本站直接点出网址造成的网站/APP等充值失败；</li></a>");
document.writeln("<a><li>5、因访问本站直接点出网址引发的其他未知损失；</li></a>");
document.writeln("<a><li>6、非本站直接点出网址不在保障范围之内！</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"add\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-trophy\" aria-hidden=\"true\"></i> 申请赔付</p>");
document.writeln("</div>");
document.writeln("<a><li>1、整理相关材料（支付截图/对话截图/对方链接地址）;</li></a>");
document.writeln("<a><li>2、将材料及申述详情发送至官方客服邮箱;</li></a>");
document.writeln("<a><li>3、客服将在3个工作日内与您主动联络沟通;</li></a>");
document.writeln("<a><li>4、经客服核实属实后将于当日全额退款至您的帐户！</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"contact\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-envelope\" aria-hidden=\"true\"></i> 赔付渠道</p>");
document.writeln("</div>");
document.writeln("<a><li>所有未尽及具体事宜，请联繫</li></a>");
document.writeln("<a><li>电子邮箱：<span style=\"color:#003399;\">500dizhi@gmail.com</span></li></a>");
document.writeln("<a><li>因客服事务繁杂，请您务必邮件标题注明链接赔付，我们将优先处理！</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate footer\">");
document.writeln("<p>CopyRight&nbsp;&nbsp;©&nbsp;&nbsp;500dh.com</p>");
document.writeln("<p> <i class=\"fa fa-home\" aria-hidden=\"true\"></i> <a href=\"../\" class=\"aboutBtn\" target=\"_blank\">返回首页</a>&nbsp;&nbsp;<i class=\"fa fa-shield\" aria-hidden=\"true\"></i> <a href=\"aq.html\" class=\"aboutBtn\" target=\"_blank\">安全保障</a>&nbsp;&nbsp;<i class=\"fa fa-plus-square\" aria-hidden=\"true\"></i> <a href=\"faq.html\" class=\"aboutBtn\" target=\"_blank\">收录合作</a></p>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<script async src=\"https://www.googletagmanager.com/gtag/js?id=G-HQDVVM82Q2\"></script>");
document.writeln("<script>");
document.writeln("  window.dataLayer = window.dataLayer || [];");
document.writeln("  function gtag(){dataLayer.push(arguments);}");
document.writeln("  gtag(\'js\', new Date());");
document.writeln("");
document.writeln("  gtag(\'config\', \'G-HQDVVM82Q2\');");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");